name: Run build
on:
  workflow_dispatch:
  schedule:
  - cron: '0 */2 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup git user
      run: |
          git config --global user.name "Lean stage0 auditor"
          git config --global user.email "<>"
    - run: git clone --single-branch https://github.com/leanprover/lean4 lean4
    - run: git -C lean4 fetch https://github.com/nomeata/lean-stage0-audit 'refs/stage0/*:refs/stage0/*'
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - run: ./enum-hashes.py > repo-digest.csv
    - run: ./website.py > index.html
    - name: Determine what to do
      run: echo "command=$(cat next-step.sh)" >> "$GITHUB_ENV"
    - run: "${{ env.command }}"
    - run: ./website.py > index.html
    - run: git commit -a -m 'Github run of ${{ env.command }}'
    - run: git pull --rebase
    - run: git push origin master 'refs/stage0/*:refs/stage0*'

