name: Run build
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - run: ./website.py > index.html
    - name: Determine what to do
      run: echo "command=$(cat next-step.sh)" >> "$GITHUB_ENV"
    - run: "${{ env.command }}"
    - run: ./website.py > index.html
    - run: git commit -a -m 'Github run of ${{ env.command }}'
    - run: git push

